### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Po-Jen** [Po-Jen/awesome-grasping#1]
Active:
- [x] https://github.com/davetcoleman/moveit_grasps

Inactive:
- [x] https://github.com/davetcoleman/moveit_simple_grasps

**Comment by Po-Jen** [comment]
Libraries:
- [x] https://github.com/atenpas/grasp_selection

Implementations:
- [x] https://github.com/dougsm/ggcnn
- [x] https://github.com/andyzeng/visual-pushing-grasping

Dataset:
- [x] https://github.com/ivalab/grasp_multiObject
